var annotated_dup =
[
    [ "Udon", null, [
      [ "Impl", null, [
        [ "E220Base", "classUdon_1_1Impl_1_1E220Base.html", "classUdon_1_1Impl_1_1E220Base" ],
        [ "PadPS5OnboardBTReader", "classUdon_1_1Impl_1_1PadPS5OnboardBTReader.html", "classUdon_1_1Impl_1_1PadPS5OnboardBTReader" ],
        [ "PadPS5OnboardUSBReader", "classUdon_1_1Impl_1_1PadPS5OnboardUSBReader.html", "classUdon_1_1Impl_1_1PadPS5OnboardUSBReader" ],
        [ "SivPadPS5Reader", "classUdon_1_1Impl_1_1SivPadPS5Reader.html", "classUdon_1_1Impl_1_1SivPadPS5Reader" ],
        [ "IsPrintableImpl", "structUdon_1_1Impl_1_1IsPrintableImpl.html", "structUdon_1_1Impl_1_1IsPrintableImpl" ],
        [ "Printer", "classUdon_1_1Impl_1_1Printer.html", "classUdon_1_1Impl_1_1Printer" ],
        [ "RoboMasterBase", "classUdon_1_1Impl_1_1RoboMasterBase.html", "classUdon_1_1Impl_1_1RoboMasterBase" ],
        [ "Deserializer", "classUdon_1_1Impl_1_1Deserializer.html", "classUdon_1_1Impl_1_1Deserializer" ],
        [ "SerializedBitSizeImpl", "structUdon_1_1Impl_1_1SerializedBitSizeImpl.html", "structUdon_1_1Impl_1_1SerializedBitSizeImpl" ],
        [ "Serializer", "classUdon_1_1Impl_1_1Serializer.html", "classUdon_1_1Impl_1_1Serializer" ],
        [ "IsSerializableImpl", "structUdon_1_1Impl_1_1IsSerializableImpl.html", "structUdon_1_1Impl_1_1IsSerializableImpl" ]
      ] ],
      [ "Message", null, [
        [ "AirCylinder", "structUdon_1_1Message_1_1AirCylinder.html", "structUdon_1_1Message_1_1AirCylinder" ],
        [ "BrushLess", "structUdon_1_1Message_1_1BrushLess.html", "structUdon_1_1Message_1_1BrushLess" ],
        [ "DistanceSensor", "structUdon_1_1Message_1_1DistanceSensor.html", "structUdon_1_1Message_1_1DistanceSensor" ],
        [ "Encoder", "structUdon_1_1Message_1_1Encoder.html", "structUdon_1_1Message_1_1Encoder" ],
        [ "Yaw", "structUdon_1_1Message_1_1Yaw.html", "structUdon_1_1Message_1_1Yaw" ],
        [ "Lcd", "structUdon_1_1Message_1_1Lcd.html", "structUdon_1_1Message_1_1Lcd" ],
        [ "Motor", "structUdon_1_1Message_1_1Motor.html", "structUdon_1_1Message_1_1Motor" ],
        [ "PadPS5", "structUdon_1_1Message_1_1PadPS5.html", "structUdon_1_1Message_1_1PadPS5" ],
        [ "PhotoSensor", "structUdon_1_1Message_1_1PhotoSensor.html", "structUdon_1_1Message_1_1PhotoSensor" ],
        [ "Servo", "structUdon_1_1Message_1_1Servo.html", "structUdon_1_1Message_1_1Servo" ],
        [ "Solenoid", "structUdon_1_1Message_1_1Solenoid.html", "structUdon_1_1Message_1_1Solenoid" ],
        [ "Stepping", "structUdon_1_1Message_1_1Stepping.html", "structUdon_1_1Message_1_1Stepping" ],
        [ "Switch", "structUdon_1_1Message_1_1Switch.html", "structUdon_1_1Message_1_1Switch" ]
      ] ],
      [ "Traits", null, [
        [ "IsPrintable", "structUdon_1_1Traits_1_1IsPrintable.html", null ],
        [ "IsSerializable", "structUdon_1_1Traits_1_1IsSerializable.html", null ],
        [ "AlwaysFalse", "structUdon_1_1Traits_1_1AlwaysFalse.html", null ],
        [ "HasMemberFunctionBegin", "structUdon_1_1Traits_1_1HasMemberFunctionBegin.html", null ],
        [ "HasMemberFunctionBegin< T, std::void_t< decltype(std::declval< T >().begin())> >", "structUdon_1_1Traits_1_1HasMemberFunctionBegin_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1d477eafb4e1e426f26cfdd9d1986528d6.html", null ],
        [ "HasMemberFunctionShow", "structUdon_1_1Traits_1_1HasMemberFunctionShow.html", null ],
        [ "HasMemberFunctionShow< T, std::void_t< decltype(std::declval< T >().show())> >", "structUdon_1_1Traits_1_1HasMemberFunctionShow_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1dea70867b32c031791c9e87d10afb768d8.html", null ],
        [ "HasMemberFunctionShowRaw", "structUdon_1_1Traits_1_1HasMemberFunctionShowRaw.html", null ],
        [ "HasMemberFunctionShowRaw< T, std::void_t< decltype(std::declval< T >().showRaw())> >", "structUdon_1_1Traits_1_1HasMemberFunctionShowRaw_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_3e444e507562d9b8f48e0eedd1a2ed7c.html", null ],
        [ "HasMemberFunctionUpdate", "structUdon_1_1Traits_1_1HasMemberFunctionUpdate.html", null ],
        [ "HasMemberFunctionUpdate< T, std::void_t< decltype(std::declval< T >().update())> >", "structUdon_1_1Traits_1_1HasMemberFunctionUpdate_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_15de3e403ae1414ee66580615516c8a49.html", null ],
        [ "DummyEnumerator", "structUdon_1_1Traits_1_1DummyEnumerator.html", "structUdon_1_1Traits_1_1DummyEnumerator" ],
        [ "HasMemberFunctionEnumerate", "structUdon_1_1Traits_1_1HasMemberFunctionEnumerate.html", null ],
        [ "HasMemberFunctionEnumerate< T, typename std::enable_if< std::is_same< decltype(std::declval< T >().enumerate(std::declval< DummyEnumerator & >())), typename DummyEnumerator::ResultType >::value >::type >", "structUdon_1_1Traits_1_1HasMemberFunctionEnumerate_3_01T_00_01typename_01std_1_1enable__if_3_01sff0f025c1d5b2a39133ed2b0fcaf15dc.html", null ],
        [ "IsOutputStreamable", "structUdon_1_1Traits_1_1IsOutputStreamable.html", null ],
        [ "IsOutputStreamable< OutputStream, T, std::void_t< decltype(std::declval< OutputStream & >()<< std::declval< T >())> >", "structUdon_1_1Traits_1_1IsOutputStreamable_3_01OutputStream_00_01T_00_01std_1_1void__t_3_01decltdeef1286ebbe867a1fa837ff072fac7c.html", null ],
        [ "IsWriter", "structUdon_1_1Traits_1_1IsWriter.html", null ],
        [ "IsWriter< T, typename std::enable_if< std::is_same< decltype(std::declval< T< int >>().setMessage(std::declval< const typename T< int >::MessageType & >())), void >::value >::type >", "structUdon_1_1Traits_1_1IsWriter_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__same_3_0c278338c0eeeac6357cf5a5cbe38e7c8.html", null ],
        [ "IsReader", "structUdon_1_1Traits_1_1IsReader.html", null ],
        [ "IsReader< T, typename std::enable_if< std::is_same< decltype(std::declval< T< int >>().getMessage()), Udon::Optional< typename T< int >::MessageType > >::value >::type >", "structUdon_1_1Traits_1_1IsReader_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__same_3_08998f18c27d3ed1ca8afdaa2586d0b7a.html", null ]
      ] ],
      [ "DeltaTime", "classUdon_1_1DeltaTime.html", "classUdon_1_1DeltaTime" ],
      [ "Input", "structUdon_1_1Input.html", "structUdon_1_1Input" ],
      [ "MovingAverage", "classUdon_1_1MovingAverage.html", "classUdon_1_1MovingAverage" ],
      [ "PidController", "classUdon_1_1PidController.html", "classUdon_1_1PidController" ],
      [ "ScopedInterruptLocker", "classUdon_1_1ScopedInterruptLocker.html", "classUdon_1_1ScopedInterruptLocker" ],
      [ "ServoSpeed", "classUdon_1_1ServoSpeed.html", "classUdon_1_1ServoSpeed" ],
      [ "SteerModuleOptimizer", "classUdon_1_1SteerModuleOptimizer.html", "classUdon_1_1SteerModuleOptimizer" ],
      [ "SteerOptimizer", "classUdon_1_1SteerOptimizer.html", "classUdon_1_1SteerOptimizer" ],
      [ "CanBusSpi", "classUdon_1_1CanBusSpi.html", "classUdon_1_1CanBusSpi" ],
      [ "CanBusTeensy", "classUdon_1_1CanBusTeensy.html", "classUdon_1_1CanBusTeensy" ],
      [ "CanReader", "classUdon_1_1CanReader.html", "classUdon_1_1CanReader" ],
      [ "CanWriter", "classUdon_1_1CanWriter.html", "classUdon_1_1CanWriter" ],
      [ "CanTxNode", "structUdon_1_1CanTxNode.html", "structUdon_1_1CanTxNode" ],
      [ "CanRxNode", "structUdon_1_1CanRxNode.html", "structUdon_1_1CanRxNode" ],
      [ "ICanBus", "classUdon_1_1ICanBus.html", "classUdon_1_1ICanBus" ],
      [ "AsyncStreamReader", "classUdon_1_1AsyncStreamReader.html", "classUdon_1_1AsyncStreamReader" ],
      [ "Forwarding", "classUdon_1_1Forwarding.html", "classUdon_1_1Forwarding" ],
      [ "EncoderBy", "classUdon_1_1EncoderBy.html", "classUdon_1_1EncoderBy" ],
      [ "MotorBy", "classUdon_1_1MotorBy.html", "classUdon_1_1MotorBy" ],
      [ "II2cBus", "classUdon_1_1II2cBus.html", "classUdon_1_1II2cBus" ],
      [ "I2cBusImpl", "classUdon_1_1I2cBusImpl.html", "classUdon_1_1I2cBusImpl" ],
      [ "I2cMasterReader", "classUdon_1_1I2cMasterReader.html", "classUdon_1_1I2cMasterReader" ],
      [ "I2cMasterWriter", "classUdon_1_1I2cMasterWriter.html", "classUdon_1_1I2cMasterWriter" ],
      [ "I2cSlaveReader", "classUdon_1_1I2cSlaveReader.html", "classUdon_1_1I2cSlaveReader" ],
      [ "I2cSlaveWriter", "classUdon_1_1I2cSlaveWriter.html", "classUdon_1_1I2cSlaveWriter" ],
      [ "Im920Node", "structUdon_1_1Im920Node.html", "structUdon_1_1Im920Node" ],
      [ "IIm920", "classUdon_1_1IIm920.html", "classUdon_1_1IIm920" ],
      [ "Im920", "classUdon_1_1Im920.html", "classUdon_1_1Im920" ],
      [ "Im920Reader", "classUdon_1_1Im920Reader.html", "classUdon_1_1Im920Reader" ],
      [ "Im920s", "classUdon_1_1Im920s.html", "classUdon_1_1Im920s" ],
      [ "Im920sL", "classUdon_1_1Im920sL.html", "classUdon_1_1Im920sL" ],
      [ "Im920Writer", "classUdon_1_1Im920Writer.html", "classUdon_1_1Im920Writer" ],
      [ "E220Reader", "classUdon_1_1E220Reader.html", "classUdon_1_1E220Reader" ],
      [ "E220Writer", "classUdon_1_1E220Writer.html", "classUdon_1_1E220Writer" ],
      [ "PadPS5", "classUdon_1_1PadPS5.html", "classUdon_1_1PadPS5" ],
      [ "PadPS5BT", "classUdon_1_1PadPS5BT.html", "classUdon_1_1PadPS5BT" ],
      [ "PadPS5USB", "classUdon_1_1PadPS5USB.html", "classUdon_1_1PadPS5USB" ],
      [ "Ros2UartReader", "classUdon_1_1Ros2UartReader.html", "classUdon_1_1Ros2UartReader" ],
      [ "Ros2UartWriter", "classUdon_1_1Ros2UartWriter.html", "classUdon_1_1Ros2UartWriter" ],
      [ "SivUartReader", "classUdon_1_1SivUartReader.html", "classUdon_1_1SivUartReader" ],
      [ "SivUartWriter", "classUdon_1_1SivUartWriter.html", "classUdon_1_1SivUartWriter" ],
      [ "UartReader", "classUdon_1_1UartReader.html", "classUdon_1_1UartReader" ],
      [ "UartWriter", "classUdon_1_1UartWriter.html", "classUdon_1_1UartWriter" ],
      [ "RoboMasterC610", "classUdon_1_1RoboMasterC610.html", "classUdon_1_1RoboMasterC610" ],
      [ "RoboMasterC620", "classUdon_1_1RoboMasterC620.html", "classUdon_1_1RoboMasterC620" ],
      [ "ArrayView", "classUdon_1_1ArrayView.html", "classUdon_1_1ArrayView" ],
      [ "EulerDirection", "structUdon_1_1EulerDirection.html", "structUdon_1_1EulerDirection" ],
      [ "Euler", "structUdon_1_1Euler.html", "structUdon_1_1Euler" ],
      [ "HSV", "structUdon_1_1HSV.html", "structUdon_1_1HSV" ],
      [ "Polar", "structUdon_1_1Polar.html", "structUdon_1_1Polar" ],
      [ "QuaternionDirection", "structUdon_1_1QuaternionDirection.html", "structUdon_1_1QuaternionDirection" ],
      [ "Quaternion", "structUdon_1_1Quaternion.html", "structUdon_1_1Quaternion" ],
      [ "RGB", "structUdon_1_1RGB.html", "structUdon_1_1RGB" ],
      [ "Vec2", "structUdon_1_1Vec2.html", "structUdon_1_1Vec2" ],
      [ "Vec3", "structUdon_1_1Vec3.html", "structUdon_1_1Vec3" ],
      [ "NulloptT", "structUdon_1_1NulloptT.html", null ],
      [ "Optional", "classUdon_1_1Optional.html", "classUdon_1_1Optional" ],
      [ "Pos", "structUdon_1_1Pos.html", "structUdon_1_1Pos" ],
      [ "RingBuffer", "classUdon_1_1RingBuffer.html", "classUdon_1_1RingBuffer" ],
      [ "StaticVector", "classUdon_1_1StaticVector.html", "classUdon_1_1StaticVector" ],
      [ "BasicStringView", "classUdon_1_1BasicStringView.html", "classUdon_1_1BasicStringView" ]
    ] ]
];