var hierarchy =
[
    [ "Udon::Message::AirCylinder", "structUdon_1_1Message_1_1AirCylinder.html", null ],
    [ "Udon::ArrayView< T >", "classUdon_1_1ArrayView.html", null ],
    [ "Udon::ArrayView< const uint8_t >", "classUdon_1_1ArrayView.html", null ],
    [ "Udon::ArrayView< uint8_t >", "classUdon_1_1ArrayView.html", null ],
    [ "Udon::AsyncStreamReader", "classUdon_1_1AsyncStreamReader.html", null ],
    [ "Udon::BasicStringView< CharType, Traits >", "classUdon_1_1BasicStringView.html", null ],
    [ "Udon::Message::BrushLess", "structUdon_1_1Message_1_1BrushLess.html", null ],
    [ "Udon::CanReader< Message >", "classUdon_1_1CanReader.html", null ],
    [ "Udon::CanRxNode", "structUdon_1_1CanRxNode.html", null ],
    [ "Udon::CanTxNode", "structUdon_1_1CanTxNode.html", null ],
    [ "Udon::CanWriter< Message >", "classUdon_1_1CanWriter.html", null ],
    [ "Udon::CanBusSpi::Config", "structUdon_1_1CanBusSpi_1_1Config.html", null ],
    [ "Udon::CanBusTeensy< Bus >::Config", "structUdon_1_1CanBusTeensy_1_1Config.html", null ],
    [ "Udon::Impl::E220Base::Config", "structUdon_1_1Impl_1_1E220Base_1_1Config.html", null ],
    [ "Udon::RingBuffer< T, Capacity >::const_iterator", "structUdon_1_1RingBuffer_1_1const__iterator.html", [
      [ "Udon::RingBuffer< T, Capacity >::iterator", "structUdon_1_1RingBuffer_1_1iterator.html", null ]
    ] ],
    [ "Udon::DeltaTime", "classUdon_1_1DeltaTime.html", null ],
    [ "Udon::Impl::Deserializer", "classUdon_1_1Impl_1_1Deserializer.html", null ],
    [ "Udon::Message::DistanceSensor", "structUdon_1_1Message_1_1DistanceSensor.html", null ],
    [ "Udon::Optional< T >::Storage::Dummy", "structUdon_1_1Optional_1_1Storage_1_1Dummy.html", null ],
    [ "Udon::Traits::DummyEnumerator", "structUdon_1_1Traits_1_1DummyEnumerator.html", null ],
    [ "Udon::Impl::E220Base", "classUdon_1_1Impl_1_1E220Base.html", [
      [ "Udon::E220Reader< T >", "classUdon_1_1E220Reader.html", null ],
      [ "Udon::E220Writer< T >", "classUdon_1_1E220Writer.html", null ]
    ] ],
    [ "Udon::Message::Encoder", "structUdon_1_1Message_1_1Encoder.html", null ],
    [ "Udon::EncoderBy< Reader >", "classUdon_1_1EncoderBy.html", null ],
    [ "Udon::Euler", "structUdon_1_1Euler.html", null ],
    [ "Udon::EulerDirection", "structUdon_1_1EulerDirection.html", null ],
    [ "std::false_type", null, [
      [ "Udon::Traits::AlwaysFalse< T >", "structUdon_1_1Traits_1_1AlwaysFalse.html", null ],
      [ "Udon::Traits::HasMemberFunctionBegin< typename, typename >", "structUdon_1_1Traits_1_1HasMemberFunctionBegin.html", null ],
      [ "Udon::Traits::HasMemberFunctionEnumerate< T, typename >", "structUdon_1_1Traits_1_1HasMemberFunctionEnumerate.html", null ],
      [ "Udon::Traits::HasMemberFunctionShow< typename, typename >", "structUdon_1_1Traits_1_1HasMemberFunctionShow.html", null ],
      [ "Udon::Traits::HasMemberFunctionShowRaw< typename, typename >", "structUdon_1_1Traits_1_1HasMemberFunctionShowRaw.html", null ],
      [ "Udon::Traits::HasMemberFunctionUpdate< typename, typename >", "structUdon_1_1Traits_1_1HasMemberFunctionUpdate.html", null ],
      [ "Udon::Traits::IsOutputStreamable< OutputStream, T, typename >", "structUdon_1_1Traits_1_1IsOutputStreamable.html", null ],
      [ "Udon::Traits::IsReader< class, typename >", "structUdon_1_1Traits_1_1IsReader.html", null ],
      [ "Udon::Traits::IsWriter< class, typename >", "structUdon_1_1Traits_1_1IsWriter.html", null ]
    ] ],
    [ "Udon::Forwarding< Reader, Writer, Message >", "classUdon_1_1Forwarding.html", null ],
    [ "Udon::HSV", "structUdon_1_1HSV.html", null ],
    [ "Udon::I2cMasterReader< Message >", "classUdon_1_1I2cMasterReader.html", null ],
    [ "Udon::I2cMasterWriter< Message >", "classUdon_1_1I2cMasterWriter.html", null ],
    [ "Udon::I2cSlaveReader< Message >", "classUdon_1_1I2cSlaveReader.html", null ],
    [ "Udon::I2cSlaveWriter< Message >", "classUdon_1_1I2cSlaveWriter.html", null ],
    [ "Udon::ICanBus", "classUdon_1_1ICanBus.html", [
      [ "Udon::CanBusSpi", "classUdon_1_1CanBusSpi.html", null ],
      [ "Udon::CanBusTeensy< Bus >", "classUdon_1_1CanBusTeensy.html", null ]
    ] ],
    [ "Udon::II2cBus", "classUdon_1_1II2cBus.html", [
      [ "Udon::I2cBusImpl< Counter >", "classUdon_1_1I2cBusImpl.html", null ]
    ] ],
    [ "Udon::IIm920", "classUdon_1_1IIm920.html", [
      [ "Udon::Im920", "classUdon_1_1Im920.html", null ],
      [ "Udon::Im920s", "classUdon_1_1Im920s.html", null ],
      [ "Udon::Im920sL", "classUdon_1_1Im920sL.html", null ]
    ] ],
    [ "Udon::Im920Node", "structUdon_1_1Im920Node.html", null ],
    [ "Udon::Im920Reader< Message >", "classUdon_1_1Im920Reader.html", null ],
    [ "Udon::Im920Writer< Message >", "classUdon_1_1Im920Writer.html", null ],
    [ "Udon::Input", "structUdon_1_1Input.html", null ],
    [ "std::integral_constant", null, [
      [ "Udon::Traits::IsPrintable< OutputStream, Args >", "structUdon_1_1Traits_1_1IsPrintable.html", null ],
      [ "Udon::Traits::IsSerializable< T >", "structUdon_1_1Traits_1_1IsSerializable.html", null ]
    ] ],
    [ "Udon::Impl::IsPrintableImpl< OutputStream >", "structUdon_1_1Impl_1_1IsPrintableImpl.html", null ],
    [ "Udon::Impl::IsSerializableImpl", "structUdon_1_1Impl_1_1IsSerializableImpl.html", null ],
    [ "Udon::Message::Lcd< Column, Row >", "structUdon_1_1Message_1_1Lcd.html", null ],
    [ "Udon::Message::Motor", "structUdon_1_1Message_1_1Motor.html", null ],
    [ "Udon::MotorBy< Writer >", "classUdon_1_1MotorBy.html", null ],
    [ "Udon::MovingAverage< DataSize >", "classUdon_1_1MovingAverage.html", null ],
    [ "Udon::NulloptT", "structUdon_1_1NulloptT.html", null ],
    [ "Udon::Optional< T >", "classUdon_1_1Optional.html", null ],
    [ "Udon::Optional< MessageType >", "classUdon_1_1Optional.html", null ],
    [ "Udon::Optional< Udon::PidController::Parameter >", "classUdon_1_1Optional.html", null ],
    [ "Udon::Optional< uint16_t >", "classUdon_1_1Optional.html", null ],
    [ "Udon::Optional< uint8_t >", "classUdon_1_1Optional.html", null ],
    [ "Udon::Message::PadPS5", "structUdon_1_1Message_1_1PadPS5.html", null ],
    [ "Udon::PadPS5BT", "classUdon_1_1PadPS5BT.html", [
      [ "Udon::Impl::PadPS5OnboardBTReader< Dummy >", "classUdon_1_1Impl_1_1PadPS5OnboardBTReader.html", null ]
    ] ],
    [ "Udon::PadPS5USB", "classUdon_1_1PadPS5USB.html", [
      [ "Udon::Impl::PadPS5OnboardUSBReader< Dummy >", "classUdon_1_1Impl_1_1PadPS5OnboardUSBReader.html", null ]
    ] ],
    [ "Udon::PidController::Parameter", "structUdon_1_1PidController_1_1Parameter.html", null ],
    [ "Udon::Message::PhotoSensor", "structUdon_1_1Message_1_1PhotoSensor.html", null ],
    [ "Udon::PidController", "classUdon_1_1PidController.html", null ],
    [ "Udon::Polar", "structUdon_1_1Polar.html", null ],
    [ "Udon::Pos", "structUdon_1_1Pos.html", null ],
    [ "Udon::Impl::Printer< OutputStream >", "classUdon_1_1Impl_1_1Printer.html", null ],
    [ "Udon::Quaternion", "structUdon_1_1Quaternion.html", null ],
    [ "Udon::QuaternionDirection", "structUdon_1_1QuaternionDirection.html", null ],
    [ "Reader", null, [
      [ "Udon::PadPS5< Reader >", "classUdon_1_1PadPS5.html", null ]
    ] ],
    [ "Udon::RGB", "structUdon_1_1RGB.html", null ],
    [ "Udon::RingBuffer< T, Capacity >", "classUdon_1_1RingBuffer.html", null ],
    [ "Udon::Impl::RoboMasterBase", "classUdon_1_1Impl_1_1RoboMasterBase.html", [
      [ "Udon::RoboMasterC610", "classUdon_1_1RoboMasterC610.html", null ],
      [ "Udon::RoboMasterC620", "classUdon_1_1RoboMasterC620.html", null ]
    ] ],
    [ "Udon::Ros2SerialReader< Message >", "classUdon_1_1Ros2SerialReader.html", null ],
    [ "Udon::Ros2SerialWriter< Message >", "classUdon_1_1Ros2SerialWriter.html", null ],
    [ "Udon::ScopedInterruptLocker", "classUdon_1_1ScopedInterruptLocker.html", null ],
    [ "Udon::Impl::SerializedBitSizeImpl", "structUdon_1_1Impl_1_1SerializedBitSizeImpl.html", null ],
    [ "Udon::Impl::Serializer", "classUdon_1_1Impl_1_1Serializer.html", null ],
    [ "Udon::SerialReader< Message >", "classUdon_1_1SerialReader.html", null ],
    [ "Udon::SerialWriter< Message >", "classUdon_1_1SerialWriter.html", null ],
    [ "Udon::Message::Servo", "structUdon_1_1Message_1_1Servo.html", null ],
    [ "Udon::ServoSpeed", "classUdon_1_1ServoSpeed.html", null ],
    [ "Udon::Impl::ShowConfig", "structUdon_1_1Impl_1_1ShowConfig.html", null ],
    [ "Udon::Impl::SivPadPS5Reader< DummyMessage >", "classUdon_1_1Impl_1_1SivPadPS5Reader.html", null ],
    [ "Udon::SivSerialReader< Message >", "classUdon_1_1SivSerialReader.html", null ],
    [ "Udon::SivSerialWriter< Message >", "classUdon_1_1SivSerialWriter.html", null ],
    [ "Udon::Message::Solenoid", "structUdon_1_1Message_1_1Solenoid.html", null ],
    [ "Udon::StaticVector< T, Capacity >", "classUdon_1_1StaticVector.html", null ],
    [ "Udon::StaticVector< can_frame, 1024 >", "classUdon_1_1StaticVector.html", null ],
    [ "Udon::StaticVector< CAN_message_t, 1024 >", "classUdon_1_1StaticVector.html", null ],
    [ "Udon::SteerModuleOptimizer", "classUdon_1_1SteerModuleOptimizer.html", null ],
    [ "Udon::SteerOptimizer< WheelCount >", "classUdon_1_1SteerOptimizer.html", null ],
    [ "Udon::Message::Stepping", "structUdon_1_1Message_1_1Stepping.html", null ],
    [ "Udon::Message::Switch", "structUdon_1_1Message_1_1Switch.html", null ],
    [ "Udon::Impl::IsPrintableImpl< OutputStream >::Test< T, typename >", "structUdon_1_1Impl_1_1IsPrintableImpl_1_1Test.html", null ],
    [ "Udon::Impl::IsSerializableImpl::Test< T, typename >", "structUdon_1_1Impl_1_1IsSerializableImpl_1_1Test.html", null ],
    [ "Udon::Impl::IsSerializableImpl::Test< Arithmetic, EnableIfVoidT< IsArithmetic< Arithmetic >::value > >", "structUdon_1_1Impl_1_1IsSerializableImpl_1_1Test_3_01Arithmetic_00_01EnableIfVoidT_3_01IsArithme904c16bf8775bc4b88a1ad244e08c1f5.html", null ],
    [ "Udon::Impl::IsSerializableImpl::Test< Array, EnableIfVoidT< IsArray< Array >::value > >", "structUdon_1_1Impl_1_1IsSerializableImpl_1_1Test_3_01Array_00_01EnableIfVoidT_3_01IsArray_3_01Array_01_4_1_1value_01_4_01_4.html", null ],
    [ "Udon::Impl::IsPrintableImpl< OutputStream >::Test< Array, EnableIfVoidT< IsArray< Array >::value and not IsCString< Array >::value and not IsOutputStreamable< OutputStream, Array >::value > >", "structUdon_1_1Impl_1_1IsPrintableImpl_1_1Test_3_01Array_00_01EnableIfVoidT_3_01IsArray_3_01Array1dba93aee3b76afe860dd5ce2e8450f1.html", null ],
    [ "Udon::Impl::IsPrintableImpl< OutputStream >::Test< Enum, EnableIfVoidT< IsEnum< Enum >::value > >", "structUdon_1_1Impl_1_1IsPrintableImpl_1_1Test_3_01Enum_00_01EnableIfVoidT_3_01IsEnum_3_01Enum_01_4_1_1value_01_4_01_4.html", null ],
    [ "Udon::Impl::IsSerializableImpl::Test< Enum, EnableIfVoidT< IsEnum< Enum >::value > >", "structUdon_1_1Impl_1_1IsSerializableImpl_1_1Test_3_01Enum_00_01EnableIfVoidT_3_01IsEnum_3_01Enum_01_4_1_1value_01_4_01_4.html", null ],
    [ "Udon::Impl::IsSerializableImpl::Test< Enumerable, EnableIfVoidT< HasMemberFunctionEnumerate< Enumerable >::value > >", "structUdon_1_1Impl_1_1IsSerializableImpl_1_1Test_3_01Enumerable_00_01EnableIfVoidT_3_01HasMemberd56c095e6f6bf13306ca5b8e672280d7.html", null ],
    [ "Udon::Impl::IsPrintableImpl< OutputStream >::Test< Enumerable, EnableIfVoidT< HasMemberFunctionEnumerate< Enumerable >::value and not HasMemberFunctionShow< Enumerable >::value and not IsOutputStreamable< OutputStream, Enumerable >::value > >", "structUdon_1_1Impl_1_1IsPrintableImpl_1_1Test_3_01Enumerable_00_01EnableIfVoidT_3_01HasMemberFun70fb8a133d43634b1e5b46a9537e3104.html", null ],
    [ "Udon::Impl::IsPrintableImpl< OutputStream >::Test< Printable, EnableIfVoidT< HasMemberFunctionShow< Printable >::value or IsOutputStreamable< OutputStream, Printable >::value > >", "structUdon_1_1Impl_1_1IsPrintableImpl_1_1Test_3_01Printable_00_01EnableIfVoidT_3_01HasMemberFunc15b5ba4bf8715386217ee42bd1ba7f8b.html", null ],
    [ "std::true_type", null, [
      [ "Udon::Traits::HasMemberFunctionBegin< T, std::void_t< decltype(std::declval< T >().begin())> >", "structUdon_1_1Traits_1_1HasMemberFunctionBegin_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1d477eafb4e1e426f26cfdd9d1986528d6.html", null ],
      [ "Udon::Traits::HasMemberFunctionEnumerate< T, typename std::enable_if< std::is_same< decltype(std::declval< T >().enumerate(std::declval< DummyEnumerator & >())), typename DummyEnumerator::ResultType >::value >::type >", "structUdon_1_1Traits_1_1HasMemberFunctionEnumerate_3_01T_00_01typename_01std_1_1enable__if_3_01sff0f025c1d5b2a39133ed2b0fcaf15dc.html", null ],
      [ "Udon::Traits::HasMemberFunctionShow< T, std::void_t< decltype(std::declval< T >().show())> >", "structUdon_1_1Traits_1_1HasMemberFunctionShow_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1dea70867b32c031791c9e87d10afb768d8.html", null ],
      [ "Udon::Traits::HasMemberFunctionShowRaw< T, std::void_t< decltype(std::declval< T >().showRaw())> >", "structUdon_1_1Traits_1_1HasMemberFunctionShowRaw_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_3e444e507562d9b8f48e0eedd1a2ed7c.html", null ],
      [ "Udon::Traits::HasMemberFunctionUpdate< T, std::void_t< decltype(std::declval< T >().update())> >", "structUdon_1_1Traits_1_1HasMemberFunctionUpdate_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_15de3e403ae1414ee66580615516c8a49.html", null ],
      [ "Udon::Traits::IsOutputStreamable< OutputStream, T, std::void_t< decltype(std::declval< OutputStream & >()<< std::declval< T >())> >", "structUdon_1_1Traits_1_1IsOutputStreamable_3_01OutputStream_00_01T_00_01std_1_1void__t_3_01decltdeef1286ebbe867a1fa837ff072fac7c.html", null ],
      [ "Udon::Traits::IsReader< T, typename std::enable_if< std::is_same< decltype(std::declval< T< int > >().getMessage()), Udon::Optional< typename T< int >::MessageType > >::value >::type >", "structUdon_1_1Traits_1_1IsReader_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__same_3_06e4865bf40f6370f1c61b96f7d348132.html", null ],
      [ "Udon::Traits::IsWriter< T, typename std::enable_if< std::is_same< decltype(std::declval< T< int > >().setMessage(std::declval< const typename T< int >::MessageType & >())), void >::value >::type >", "structUdon_1_1Traits_1_1IsWriter_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__same_3_0e17e1ac5ec2035eb8694217d994bebd1.html", null ]
    ] ],
    [ "Udon::Vec2", "structUdon_1_1Vec2.html", null ],
    [ "Udon::Vec3", "structUdon_1_1Vec3.html", null ],
    [ "Udon::Message::Yaw", "structUdon_1_1Message_1_1Yaw.html", null ]
];