var searchData=
[
  ['dip_20スイッチ_0',['DIP スイッチ',['../md_docs_2Driver_2DipSwitch.html',1,'']]],
  ['distancefrom_20vec2_20other_20double_1',['&lt;span class=&quot;tt&quot;&gt;distanceFrom(Vec2 other) -&amp;gt; double&lt;/span&gt;',['../md_docs_2Types_2Vector2D.html#autotoc_md316',1,'']]],
  ['double_2',['double',['../md_docs_2Types_2Vector2D.html#autotoc_md319',1,'&lt;span class=&quot;tt&quot;&gt;angle() -&amp;gt; double&lt;/span&gt;'],['../md_docs_2Types_2Vector2D.html#autotoc_md318',1,'&lt;span class=&quot;tt&quot;&gt;angleAt(Vec2 other) -&amp;gt; double&lt;/span&gt;'],['../md_docs_2Types_2Vector2D.html#autotoc_md316',1,'&lt;span class=&quot;tt&quot;&gt;distanceFrom(Vec2 other) -&amp;gt; double&lt;/span&gt;'],['../md_docs_2Types_2Vector2D.html#autotoc_md315',1,'&lt;span class=&quot;tt&quot;&gt;length() -&amp;gt; double&lt;/span&gt;']]],
  ['double_20angle_20vec2_3',['double angle Vec2',['../md_docs_2Types_2Vector2D.html#autotoc_md325',1,'&lt;span class=&quot;tt&quot;&gt;rotate(double angle) -&amp;gt; Vec2&amp;amp;&lt;/span&gt;'],['../md_docs_2Types_2Vector2D.html#autotoc_md328',1,'&lt;span class=&quot;tt&quot;&gt;rotateAt(Vec2 center, double angle) -&amp;gt; Vec2&amp;amp;&lt;/span&gt;'],['../md_docs_2Types_2Vector2D.html#autotoc_md324',1,'&lt;span class=&quot;tt&quot;&gt;rotated(double angle) -&amp;gt; Vec2&lt;/span&gt;'],['../md_docs_2Types_2Vector2D.html#autotoc_md327',1,'&lt;span class=&quot;tt&quot;&gt;rotatedAt(Vec2 center, double angle) -&amp;gt; Vec2&lt;/span&gt;']]],
  ['double_20frommax_20double_20tomin_20double_20tomax_20vec2_4',['double fromMax double toMin double toMax Vec2',['../md_docs_2Types_2Vector2D.html#autotoc_md336',1,'&lt;span class=&quot;tt&quot;&gt;map(double fromMin, double fromMax, double toMin, double toMax) -&amp;gt; Vec2&amp;amp;&lt;/span&gt;'],['../md_docs_2Types_2Vector2D.html#autotoc_md335',1,'&lt;span class=&quot;tt&quot;&gt;mapped(double fromMin, double fromMax, double toMin, double toMax) -&amp;gt; Vec2&lt;/span&gt;']]],
  ['double_20frommin_20double_20frommax_20double_20tomin_20double_20tomax_20vec2_5',['double fromMin double fromMax double toMin double toMax Vec2',['../md_docs_2Types_2Vector2D.html#autotoc_md336',1,'&lt;span class=&quot;tt&quot;&gt;map(double fromMin, double fromMax, double toMin, double toMax) -&amp;gt; Vec2&amp;amp;&lt;/span&gt;'],['../md_docs_2Types_2Vector2D.html#autotoc_md335',1,'&lt;span class=&quot;tt&quot;&gt;mapped(double fromMin, double fromMax, double toMin, double toMax) -&amp;gt; Vec2&lt;/span&gt;']]],
  ['double_20length_20vec2_6',['double length Vec2',['../md_docs_2Types_2Vector2D.html#autotoc_md321',1,'&lt;span class=&quot;tt&quot;&gt;scaledLength(double length) -&amp;gt; Vec2&lt;/span&gt;'],['../md_docs_2Types_2Vector2D.html#autotoc_md322',1,'&lt;span class=&quot;tt&quot;&gt;scaleLength(double length) -&amp;gt; Vec2&amp;amp;&lt;/span&gt;']]],
  ['double_20max_20vec2_7',['double max Vec2',['../md_docs_2Types_2Vector2D.html#autotoc_md333',1,'&lt;span class=&quot;tt&quot;&gt;clamp(double min, double max) -&amp;gt; Vec2&amp;amp;&lt;/span&gt;'],['../md_docs_2Types_2Vector2D.html#autotoc_md332',1,'&lt;span class=&quot;tt&quot;&gt;clamped(double min, double max) -&amp;gt; Vec2&lt;/span&gt;']]],
  ['double_20min_20double_20max_20vec2_8',['double min double max Vec2',['../md_docs_2Types_2Vector2D.html#autotoc_md333',1,'&lt;span class=&quot;tt&quot;&gt;clamp(double min, double max) -&amp;gt; Vec2&amp;amp;&lt;/span&gt;'],['../md_docs_2Types_2Vector2D.html#autotoc_md332',1,'&lt;span class=&quot;tt&quot;&gt;clamped(double min, double max) -&amp;gt; Vec2&lt;/span&gt;']]],
  ['double_20tomax_20vec2_9',['double toMax Vec2',['../md_docs_2Types_2Vector2D.html#autotoc_md336',1,'&lt;span class=&quot;tt&quot;&gt;map(double fromMin, double fromMax, double toMin, double toMax) -&amp;gt; Vec2&amp;amp;&lt;/span&gt;'],['../md_docs_2Types_2Vector2D.html#autotoc_md335',1,'&lt;span class=&quot;tt&quot;&gt;mapped(double fromMin, double fromMax, double toMin, double toMax) -&amp;gt; Vec2&lt;/span&gt;']]],
  ['double_20tomin_20double_20tomax_20vec2_10',['double toMin double toMax Vec2',['../md_docs_2Types_2Vector2D.html#autotoc_md336',1,'&lt;span class=&quot;tt&quot;&gt;map(double fromMin, double fromMax, double toMin, double toMax) -&amp;gt; Vec2&amp;amp;&lt;/span&gt;'],['../md_docs_2Types_2Vector2D.html#autotoc_md335',1,'&lt;span class=&quot;tt&quot;&gt;mapped(double fromMin, double fromMax, double toMin, double toMax) -&amp;gt; Vec2&lt;/span&gt;']]],
  ['doxygen_20のメリット_11',['Doxygen のメリット',['../md_docs_2Developer_2DoxygenPage.html#autotoc_md142',1,'']]],
  ['doxygen_20コメントの書き方_12',['Doxygen コメントの書き方',['../md_docs_2Developer_2DoxygenPage.html#autotoc_md140',1,'']]]
];
